services:
  eureka-server:
    build: 
        context: ./backend
        dockerfile: eureka-server/Dockerfile
    ports:
      - "8761:8761"
    networks:
      - backend-network

  gateway:
    build: 
       context: ./backend
       dockerfile: gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - backend-network

  modulorubricacriterio:
    build: 
       context: ./backend
       dockerfile: ModuloRubricaCriterio/Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - eureka-server
      - mariadb
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    networks:
      - backend-network

  evaluation-service:
    build: 
       context: ./backend
       dockerfile: evaluation-service/Dockerfile
    ports:
      - "5002:5002"
    depends_on:
      - eureka-server
      - mariadb
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    networks:
      - backend-network

  mariadb:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: unicauca
    ports:
      - "3306:3306"
    networks:
      - backend-network

  # frontend:
    # build:
      # context: ./frontend
      # dockerfile: Dockerfile
    # ports:
      # - "80:80"
    # depends_on:
      # - gateway
    # networks:
      # - backend-network

networks:
  backend-network:
    driver: bridge
