services:
  ### Keycloak conectado a PostgreSQL en AWS RDS
  keycloak:
    container_name: keycloak_sga
    image: quay.io/keycloak/keycloak:26.2.0
    command: [ "start-dev" ]
    ports:
      - "8181:8181"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://${KEYCLOAK_DB_HOST}:${KEYCLOAK_DB_PORT}/${KEYCLOAK_DB_NAME}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_DB_SCHEMA: ${KEYCLOAK_DB_SCHEMA}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HTTP_PORT: 8181
      KC_HOSTNAME: keycloak.local
    networks:
      - backend-network
    volumes:
      - keycloak_data_sga:/opt/keycloak/data

  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - backend-network

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - backend-network

  modulorubricacriterio:
    build: ./ModuloRubricaCriterio_Hexagonal
    ports:
      - "5001:5001"
    depends_on:
      - eureka-server
      - mariadb   # 👈 importante para que espere a la base de datos
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    networks:
      - backend-network

  evaluation-service:
    build: ./evaluation-service
    ports:
      - "5002:5002"
    depends_on:
      - eureka-server
      - mariadb
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    networks:
      - backend-network

  helper-service:
    build: ./helper-service
    ports:
      - "5004:5004"
    depends_on:
      - eureka-server
      - helper_mariadb
      - evaluation-service
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL_HELPER}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    networks:
      - backend-network

  mariadb:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: unicauca     # This could be changed for another name.
    ports:
      - "3306:3306"  # Maybe this port isn't the original port. Change it.
    networks:
      - backend-network

  helper_mariadb:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: unicauca
    ports:
      - "3308:3306"
    networks:
      - backend-network

  rabbit:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=unicauca
      - RABBITMQ_DEFAULT_PASS=unicaucaRabbit
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  keycloak_data_sga: