services:
  keycloak:
    env_file:
      - .env
    container_name: keycloak_sga
    image: quay.io/keycloak/keycloak:26.2.0
    command: [ "start-dev" ]
    restart: always
    ports:
      - "8181:8181"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://${KEYCLOAK_DB_HOST}:${KEYCLOAK_DB_PORT}/${KEYCLOAK_DB_NAME}?sslmode=require
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_DB_SCHEMA: ${KEYCLOAK_DB_SCHEMA}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HTTP_PORT: 8181
      KC_HOSTNAME: keycloak.local
    networks:
      - backend-network
    volumes:
      - keycloak_data_sga:/opt/keycloak/data

  auth-service:
    env_file:
      - .env
    container_name: auth-service-sga
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - keycloak
    environment:
      KC_CLIENT_SECRET: ${KC_CLIENT_SECRET}
    networks:
      - backend-network
    extra_hosts:
      - "keycloak.local:host-gateway"

  eureka-server:
    env_file:
      - .env
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - backend-network
    environment:
      EUREKA_USERNAME: ${EUREKA_USERNAME}
      EUREKA_PASSWORD: ${EUREKA_PASSWORD}

  gateway:
    env_file:
      - .env
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway-sga
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - keycloak
    networks:
      - backend-network
    extra_hosts:
      - "keycloak.local:host-gateway"
    environment:
      EUREKA_USERNAME: ${EUREKA_USERNAME}
      EUREKA_PASSWORD: ${EUREKA_PASSWORD}
      KC_CLIENT_SECRET: ${KC_CLIENT_SECRET}
      ACTIVE_PROFILE: docker

  modulorubricacriterio:
    env_file:
      - .env
    build:
      context: ./ModuloRubricaCriterio
      dockerfile: Dockerfile
    container_name: modulorubricacriterio
    ports:
      - "0:5001"
    depends_on:
      eureka-server:
        condition: service_started
      gateway:
        condition: service_started
    healthcheck:
      test: |
        curl -sSf http://localhost:5001/actuator/health | grep -q '"db":{"status":"UP"}' || exit 1
      interval: 15s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    environment:
      EVALUATION_DATASOURCE_URL: ${EVALUATION_DOCKER_DATASOURCE_URL}
      EVALUATION_DATASOURCE_USERNAME: ${EVALUATION_DATASOURCE_USERNAME}
      EVALUATION_DATASOURCE_PASSWORD: ${EVALUATION_DATASOURCE_PASSWORD}
      EUREKA_USERNAME: ${EUREKA_USERNAME}
      EUREKA_PASSWORD: ${EUREKA_PASSWORD}
      ACTIVE_PROFILE: docker
    networks:
      - backend-network

  evaluation-service:
    env_file:
      - .env
    build:
      context: ./evaluation-service
      dockerfile: Dockerfile
    container_name: evaluation-service
    ports:
      - "0:5002"
    depends_on:
      eureka-server:
        condition: service_started
      gateway:
        condition: service_started
    healthcheck:
      test: |
        curl -sSf http://localhost:5002/actuator/health | grep -q '"db":{"status":"UP"}' || exit 1
      interval: 15s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    environment:
      EVALUATION_DATASOURCE_URL: ${EVALUATION_DOCKER_DATASOURCE_URL}
      EVALUATION_DATASOURCE_USERNAME: ${EVALUATION_DATASOURCE_USERNAME}
      EVALUATION_DATASOURCE_PASSWORD: ${EVALUATION_DATASOURCE_PASSWORD}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      EUREKA_USERNAME: ${EUREKA_USERNAME}
      EUREKA_PASSWORD: ${EUREKA_PASSWORD}
      ACTIVE_PROFILE: docker
    networks:
      - backend-network

  common-utilities-service:
    env_file:
      - .env
    build:
        context: ./common-utilities-service
        dockerfile: Dockerfile
    container_name: common-utilities-service
    ports:
      - "0:5004"
    depends_on:
      eureka-server:
        condition: service_started
      gateway:
        condition: service_started
      evaluation-service:
        condition: service_started
    healthcheck:
      test: |
        curl -sSf http://localhost:5004/actuator/health | grep -q '"db":{"status":"UP"}' || exit 1
      interval: 15s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    environment:
      COMMON_DATASOURCE_URL: ${COMMON_DOCKER_DATASOURCE_URL}
      COMMON_DATASOURCE_USERNAME: ${COMMON_DATASOURCE_USERNAME}
      COMMON_DATASOURCE_PASSWORD: ${COMMON_DATASOURCE_PASSWORD}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      EUREKA_USERNAME: ${EUREKA_USERNAME}
      EUREKA_PASSWORD: ${EUREKA_PASSWORD}
      ACTIVE_PROFILE: docker
      SPRING_RABBITMQ_HOST: rabbit
    networks:
      - backend-network

  rabbit-1:
    image: rabbitmq:3.12-management
    container_name: rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      backend-network:
        aliases:
          - rabbit

networks:
  backend-network:
    driver: bridge

volumes:
  keycloak_data_sga: