name: Backend CI/CD

on:
  push:
    branches: [ main, auth-WTF ]
    paths: 
      - 'backend/**'
      - '!backend/**/*.md'  # Ignora archivos no relevantes

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Git permissions
      run: |
        git config --global --add safe.directory /home/runner/work/your-repo/your-repo
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-

    - name: Build JARs
      run: |
        cd backend
        if git diff --name-only HEAD^ HEAD | grep -E 'src/|pom.xml'; then
          chmod +x build-jar.sh
          ./build-jar.sh
        else
          echo "No hay cambios relevantes en el backend. Saltando construccion de JARs."
        fi

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /home/Proyecto1/backend
          docker compose build --no-cache
          docker compose up -d
