name: Frontend CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ main, auth-WTF ]
    paths: 
      - 'frontend/**'
      - '!frontend/**/*.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
            cd /home/Sistema-de-Gestion-Academica
            git pull origin main
            
            cd frontend
            if git diff --name-only HEAD^ HEAD | grep 'package-lock.json'; then
              npm i
            fi          
            docker rm -f frontend-dev || true
            docker build -t frontend-dev ./frontend
            
            docker run -d \
              --name frontend-dev \
              -p 3000:3000 \
              frontend-dev